"""
rop/guidance/answerer.py

Stage 2 of RoP — Guided Answering.

Applies the auto-generated guidance instruction (inopt) to the corrected
question and extracts the final predicted answer.

Supports two answer extraction modes:
  - "multiple_choice": extracts A/B/C/D/E from the response (AQUA, CSQA, …)
  - "numeric":         extracts the last number from the response (GSM8K, …)
"""

import logging
import re
from typing import Optional

from rop.llm.client import LLMClient

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Answer extraction helpers
# ---------------------------------------------------------------------------

def _parse_options(question: str) -> dict[str, str]:
    """Return a letter→value mapping from answer choice text in *question*."""
    pattern = r"\([A-F]\)\s*([^()]+?)(?=\s*\([A-F]\)|\s*$)"
    options = re.findall(pattern, question)
    return {chr(65 + i): opt.strip() for i, opt in enumerate(options)}


def _to_number(s: str) -> float:
    return float(s.replace("%", "").replace("$", "").strip())


def extract_multiple_choice(response: str, question: str) -> Optional[str]:
    """
    Extract the predicted answer letter (A–F) from *response*.

    Strategy (in priority order):
      1. \\boxed{} content — numeric or letter match against options
      2. Last standalone letter A–F in response
      3. Last option value string found in response
    """
    option_dict = _parse_options(question)

    # 1. Boxed content
    boxed = re.search(r"\\boxed\{(.+?)\}", response)
    if boxed:
        content = re.sub(r"\\text\{.*?\}", "", boxed.group(1)).strip()

        if re.match(r"^[A-F]$", content):
            return content

        try:
            boxed_num = _to_number(content)
            for letter, val in option_dict.items():
                if abs(boxed_num - _to_number(val)) < 0.01:
                    return letter
        except ValueError:
            pass

        for letter, val in option_dict.items():
            if content in val or val in content:
                return letter

    # 2. Last standalone letter
    letters = re.findall(r"\b[A-F]\b", response)
    if letters:
        return letters[-1]

    # 3. Option value match (reverse order = prefer later options)
    flat = response.replace("\n", " ")
    for letter, val in reversed(option_dict.items()):
        if val in flat:
            return letter
        try:
            num = float(re.sub(r"[^\d.]", "", val))
            if re.search(r"\b" + re.escape(str(num)) + r"\b", flat):
                return letter
        except ValueError:
            continue

    return None


def extract_numeric(response: str) -> Optional[str]:
    """
    Extract a numeric answer from *response*.

    Handles the common CoT pattern where the last line contains the answer,
    sometimes expressed as a fraction (e.g. "12/4").
    """
    lines = [ln for ln in response.strip(".").replace(",", "").split("\n") if ln]
    if not lines:
        return None

    last = lines[-1]
    nums = re.findall(r"-?\d+\.?\d*", last)

    if len(nums) == 2 and "/" in last:
        try:
            return str(float(nums[0]) / float(nums[1]))
        except ZeroDivisionError:
            pass

    if len(nums) == 2:
        return nums[0]

    # Fall back: last number in the full response
    all_nums = re.findall(r"-?\d+\.?\d*", response.replace(",", ""))
    if not all_nums:
        return None
    result = all_nums[-1]
    return result.rstrip(".")


# ---------------------------------------------------------------------------
# Main answerer class
# ---------------------------------------------------------------------------

class Answerer:
    """
    Generates answers for corrected questions using a guidance instruction.

    Args:
        client:      LLMClient configured with the evaluator model (GPT-3.5).
        instruction: The guidance instruction generated by APE.
        answer_type: "multiple_choice" or "numeric".
    """

    def __init__(self, client: LLMClient, instruction: str, answer_type: str = "multiple_choice"):
        self.client = client
        self.instruction = instruction.strip()
        if answer_type not in ("multiple_choice", "numeric"):
            raise ValueError(f"answer_type must be 'multiple_choice' or 'numeric', got '{answer_type}'")
        self.answer_type = answer_type

    def answer(self, corrected_question: str) -> tuple[Optional[str], str]:
        """
        Generate and parse an answer for *corrected_question*.

        Returns:
            (predicted_answer, raw_response)
            predicted_answer is None if extraction failed.
        """
        prompt = self.instruction + " " + corrected_question
        raw = self.client.complete(prompt) or ""

        if self.answer_type == "multiple_choice":
            pred = extract_multiple_choice(raw, corrected_question)
        else:
            pred = extract_numeric(raw)

        return pred, raw
