"""
rop/correction/corrector.py

Stage 1 of RoP — Error Correction.

Applies the auto-generated error correction instruction to a perturbed
question, producing a semantically restored version that can be passed
to the Guidance stage.

The corrector also handles post-processing quirks specific to multiple-
choice datasets (e.g., re-attaching answer choices if the LLM drops them).
"""

import logging
import re
from typing import Optional

from rop.llm.client import LLMClient

logger = logging.getLogger(__name__)


def _clean_llm_output(text: str) -> str:
    """
    Strip formatting artefacts that LLMs sometimes add:
    - "---" delimiters
    - Preamble lines such as "Here is the corrected version:\n\n"

    Returns the cleaned body text.
    """
    # Pattern 1: exactly two "---" fences with minimal headers
    if text.count("---") == 2 and text.count("###") < 3:
        inner = text.split("---")[1]
        inner = inner.replace("\n", " ")
        return " ".join(inner.split()).strip()

    # Pattern 2: single "---" with a ":\n\n" preamble
    if text.count("---") == 1 and text.count(":\n\n") == 1:
        text = text.split("---")[1]

    # Strip "Label:\n\n" preamble and "Label:\n\n" suffix
    first = text.find(":\n\n")
    if first == -1:
        return text

    body = text[first + 2 :]
    last = body.rfind(":\n\n")
    if last != -1:
        body = body[:last]

    # Collapse whitespace
    body = body.replace("---", "").replace("\n", " ")
    return " ".join(body.split())


def _restore_answer_choices(corrected: str, original_question: str) -> str:
    """
    If the LLM dropped the "Answer Choices:" block during correction,
    extract it from the original question and re-attach it.
    """
    choice_markers = ("Answer Choices", "Answer choices", "answer choices")
    if any(m in corrected for m in choice_markers):
        return corrected  # already present

    idx = original_question.find("Answer Choices:")
    if idx != -1:
        choices = original_question[idx:].strip()
        corrected = corrected.strip() + " " + choices
    return corrected


class Corrector:
    """
    Applies an error correction instruction (inec) to perturbed inputs.

    The instruction is generated externally by the APE module and stored
    in the experiment's result directory. Pass it here as a plain string.
    """

    def __init__(self, client: LLMClient, instruction: str, max_retries: int = 3):
        """
        Args:
            client:      LLMClient configured with the optimizer model (GPT-4o).
            instruction: The error correction instruction generated by APE.
            max_retries: How many times to retry if the LLM returns empty output.
        """
        self.client = client
        self.instruction = instruction.strip()
        self.max_retries = max_retries

    def correct(self, perturbed_question: str, original_question: str = "") -> str:
        """
        Correct a perturbed question.

        Args:
            perturbed_question: The adversarially perturbed input.
            original_question:  The original clean question (used only to
                                restore answer choices if they go missing).

        Returns:
            Corrected question string. Falls back to "." if all attempts fail.
        """
        prompt = self.instruction + "\n\n" + perturbed_question

        for attempt in range(self.max_retries):
            response = self.client.complete(prompt)

            if response and response.strip():
                corrected = _clean_llm_output(response).strip()
                corrected = _restore_answer_choices(corrected, original_question)
                return corrected

            logger.warning(
                "Correction attempt %d/%d returned empty output.",
                attempt + 1,
                self.max_retries,
            )

        logger.error("All correction attempts failed. Returning placeholder.")
        return "."
